version: 2.1
orbs:
  brew: circleci/shellcheck@1.3.16
parameters:
  branch-name:
    type: string
    default: "RC-0.4.0"
jobs:
  brew:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run: apk add curl perl-utils git openssh-client
      - run: sh update_brew.sh << pipeline.parameters.branch-name >>
      - run:
          name: Commit to GitHub
          command: |
            git config user.email "$GH_EMAIL"
            git config user.name "CircleCI Job"
            git checkout circleci-project-setup
            git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
            git push origin circleci-project-setup
workflows:
  brew:
    jobs:
      - brew

